### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '../data/caffe_layers_value.pickle'

### ISSUE THREAD

**Issue by rambow330** [jazzsaxmafia/Weakly_detector#8]
File "train.caltech.py", line 67, in <module>
    detector = Detector(weight_path, n_labels)
  File "/home/spark/Weakly_detector/src/detector.py", line 10, in __init__
    with open(weight_file_path) as f:
IOError: [Errno 2] No such file or directory: '../data/caffe_layers_value.pickle'

can you tell me how to slove this?
thanks

**Comment by alseambusher** [comment]
Use [VGG](https://drive.google.com/file/d/0B5o40yxdA9PqOVI5dF9tN3NUc2c/view?usp=sharing) shared by the developer and place it in the data folder.

**Comment by panyongfeng** [comment]
the link is broken, can you share it again, thanks
